### PR TITLE
Replace Doxygen button with Doc linters

### PR DESCRIPTION
**Pull request by albtam**
This change is [Reviewable](https://reviewable.io/reviews/apexai/ros2_clion_style/23)

### CODE REVIEW

**Review by MichaelOrlov — APPROVED** [review]
@albtam I've checked the script in my local CLion and it works as expected. i.e. it's running linters.   
However I would keep old `Doxygen` icon for button, but with new name and popup hint "Doc linters".

**Comment by albtam** [comment]
@MichaelOrlov Thanks!

> However I would keep old Doxygen icon for button, but with new name and popup hint "Doc linters".

I am not sure to understand that. The doc linters script has nothing to do with Doxygen. It does not build the documentation at all. We now have too many options to build the doc, that's why I think it is better to run the script in the console instead of having too many buttons.

**Comment by MichaelOrlov** [comment]
@albtam I agree with you that it's better to run script in console to build the docs.  
However, IMO button with word **Doxygen** associates with running linters for documents rather than expecting to make a build for docs.  
i.e. The button for running docs specific linters for checking docs files to be ready for commit. Aka check documentation files to be ready.

**Comment by albtam** [comment]
@MichaelOrlov I prefer to leave it as it is in the PR. Let's change it if people start complaining. Can you please merge the pull request if it is fine for you?

**Pull request merged**
